// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHgg5VkIPu5k_pbs9vaFYd9Bs3Vv6LF8M',
    appId: '1:999830538320:web:1716b391d4946c1cc02955',
    messagingSenderId: '999830538320',
    projectId: 'c3-proj-a9f27',
    authDomain: 'c3-proj-a9f27.firebaseapp.com',
    storageBucket: 'c3-proj-a9f27.firebasestorage.app',
    measurementId: 'G-WYCT07F2PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBit2kPnTTStjmAOAgHCUyTcABGTkoZmDI',
    appId: '1:999830538320:android:4a31c3c5a0150e97c02955',
    messagingSenderId: '999830538320',
    projectId: 'c3-proj-a9f27',
    storageBucket: 'c3-proj-a9f27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNjxPLIqJ1whW9zr18_-Egub4iOZcdBB8',
    appId: '1:999830538320:ios:298db1b3dcf791acc02955',
    messagingSenderId: '999830538320',
    projectId: 'c3-proj-a9f27',
    storageBucket: 'c3-proj-a9f27.firebasestorage.app',
    iosClientId: '999830538320-3olbli3j5vcuq1jp1gjqcuqkh02tgjlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicsapp',
  );
}
